# Generated by Django 4.2.13 on 2024-07-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(default='', max_length=25)),
                ('Lastname', models.CharField(default='', max_length=25)),
                ('Email', models.CharField(default='', max_length=50)),
                ('Password', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
